apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}-cont
        image: {{ .Values.flask_app.image }}
        ports:
        - containerPort: {{ .Values.flask_app.port }}
        env:
        - name: FILE_PATH
          value: "{{ .Values.configmap.configmap_mountpath }}/{{ .Values.configmap.configmap_data.filename }}"
        volumeMounts:
        - name: config-volume
          mountPath: "{{ .Values.configmap.configmap_mountpath  }}"
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.name }}-configmap